version: '3.8'

services:
  newsanalyze-service: 
    build: .
    ports:
      - "127.0.0.1:36694:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3