services:
  internal-proxy:
    image: traefik:latest
    command:
      - --entrypoints.webinternal.address=:80
    ports:
      - "127.0.0.1:36694:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app-network
  newsanalyze-service:
    build: .
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.newsanalyze.rule=Host(`news.yuanhau.com`)"
      - "traefik.http.routers.newsanalyze.entrypoints=webinternal"
      - "traefik.http.services.newsanalyze.loadbalancer.server.port=3000"

networks:
  app-network:
    driver: bridge
