services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 127.0.0.1:36694:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

  newsanalyze-service:
    image: ghcr.io/hpware/news-analyze:master
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.newsanalyze.rule=Host(`news.yuanhau.com`)"
      - "traefik.http.services.newsanalyze.loadbalancer.server.port=3000"
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 2

networks:
  web:
